# Generated by Django 5.1.1 on 2024-10-08 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldoku', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eigene',
            options={'ordering': ['gruppe'], 'verbose_name': 'Eigene', 'verbose_name_plural': 'Eigene'},
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Bezeichnung')),
                ('standort', models.CharField(max_length=50, verbose_name='Standort')),
                ('beschreibung', models.TextField(blank=True, null=True, verbose_name='Informationen')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Leiter')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Gruppe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Name')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ldoku.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Gruppe',
                'verbose_name_plural': 'Gruppen',
            },
        ),
        migrations.CreateModel(
            name='Teamzuordnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gruppe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ldoku.gruppe', verbose_name='Gruppe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ausbilder')),
            ],
            options={
                'verbose_name': 'Teamzuordnung',
                'verbose_name_plural': 'Teamzuordnungen',
            },
        ),
    ]
