# Generated by Django 5.1.1 on 2024-10-08 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldoku', '0002_alter_eigene_options_team_gruppe_teamzuordnung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamzuordnung',
            name='gruppe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ldoku.team', verbose_name='Gruppe'),
        ),
    ]
