# Generated by Django 5.1.1 on 2024-10-08 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ldoku', '0003_alter_teamzuordnung_gruppe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamzuordnung',
            options={'ordering': ['user'], 'verbose_name': 'Teamzuordnung', 'verbose_name_plural': 'Teamzuordnungen'},
        ),
    ]
