# Generated by Django 5.1.1 on 2024-10-08 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ldoku', '0004_alter_teamzuordnung_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamzuordnung',
            old_name='gruppe',
            new_name='team',
        ),
    ]
