# Generated by Django 5.1.1 on 2025-06-30 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ausbilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuerzel', models.CharField(max_length=10, verbose_name='Kürzel')),
                ('color', models.CharField(max_length=20, verbose_name='Farbe')),
                ('beschreibung', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('activ', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='User2', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Ausbilder',
                'verbose_name_plural': 'Ausbilder',
                'ordering': ['user'],
            },
        ),
    ]
