# Generated by Django 5.1.1 on 2025-06-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stammdaten', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausbilder',
            name='fg_color',
            field=models.CharField(default='black', max_length=50, verbose_name='Schriftfarbe'),
        ),
    ]
