# Generated by Django 5.1.1 on 2024-10-17 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beruf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurz', models.CharField(max_length=10, verbose_name='Abkürzung')),
                ('lang', models.CharField(max_length=250, verbose_name='Langform')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Info')),
            ],
            options={
                'verbose_name': 'Beruf',
                'verbose_name_plural': 'Berufe',
            },
        ),
        migrations.CreateModel(
            name='Schlagwort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Bezeichnung')),
                ('beschreibung', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Schlagwort',
                'verbose_name_plural': 'Schlagwörter',
            },
        ),
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50, verbose_name='Titel')),
                ('datum', models.DateField(verbose_name='Datum')),
                ('pdf_frage', models.FileField(blank=True, null=True, upload_to=None, verbose_name='Datei Fragen')),
                ('pdf_antwort', models.FileField(blank=True, null=True, upload_to=None, verbose_name='Datei Lösungen')),
                ('beruf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pruefung.beruf', verbose_name='Beruf')),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumente',
            },
        ),
        migrations.CreateModel(
            name='Frage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=50, verbose_name='Titel')),
                ('nummer', models.CharField(max_length=50, verbose_name='Nummer')),
                ('beschreibung', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('frage', models.ImageField(upload_to=None, verbose_name='Frage Bild')),
                ('antwort', models.ImageField(upload_to=None, verbose_name='Antwort Bild')),
                ('quelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Frage', to='pruefung.dokument', verbose_name='Quelle')),
                ('stichworte', models.ManyToManyField(to='pruefung.schlagwort', verbose_name='Schlagwörter')),
            ],
            options={
                'verbose_name': 'Frage',
                'verbose_name_plural': 'Fragen',
            },
        ),
    ]
