# Generated by Django 4.2.7 on 2023-11-08 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thema',
            fields=[
                ('titel', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Titel')),
                ('kommentar', models.TextField(verbose_name='Kommentar')),
            ],
            options={
                'verbose_name': 'Thema',
                'verbose_name_plural': 'Themas',
                'ordering': ['titel'],
            },
        ),
        migrations.CreateModel(
            name='Frage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=50, verbose_name='Titel')),
                ('frage', models.TextField(verbose_name='Frage')),
                ('musterantwort', models.TextField(verbose_name='Musterantwort')),
                ('bild', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Bild')),
                ('punkte', models.IntegerField(verbose_name='Erreichbare Punkte')),
                ('platz', models.IntegerField(default=2, verbose_name='Platz')),
                ('thema', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='klausur.thema', verbose_name='Thema')),
            ],
            options={
                'verbose_name': 'Frage',
                'verbose_name_plural': 'Fragen',
                'ordering': ['thema', 'titel'],
            },
        ),
    ]
