# Generated by Django 4.2.7 on 2023-11-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klausur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thema',
            name='kommentar',
            field=models.TextField(blank=True, null=True, verbose_name='Kommentar'),
        ),
    ]
