# Generated by Django 4.2.7 on 2023-11-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klausur', '0002_alter_thema_kommentar'),
    ]

    operations = [
        migrations.AddField(
            model_name='frage',
            name='schwierigkeit',
            field=models.IntegerField(default=2, verbose_name='Schwierigkeit'),
        ),
    ]
