# Generated by Django 4.2.7 on 2023-11-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klausur', '0003_frage_schwierigkeit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frage',
            name='titel',
            field=models.CharField(max_length=250, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='thema',
            name='titel',
            field=models.CharField(max_length=250, primary_key=True, serialize=False, verbose_name='Titel'),
        ),
    ]
