# Generated by Django 4.2.7 on 2023-11-20 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klausur', '0005_klausur_klausurthema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klausurthema',
            options={'ordering': ['klausur', 'position'], 'verbose_name': 'Klausur-Thema', 'verbose_name_plural': 'Klausur-Themen'},
        ),
    ]
