# Generated by Django 4.2.7 on 2023-11-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klausur', '0006_alter_klausurthema_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klausur',
            options={'ordering': ['-termin'], 'verbose_name': 'Klausur', 'verbose_name_plural': 'Klausuren'},
        ),
        migrations.AddField(
            model_name='frage',
            name='inhalt',
            field=models.CharField(default='?', max_length=20, verbose_name='Inhalt'),
        ),
    ]
