# Generated by Django 4.2.7 on 2023-11-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klausur', '0007_alter_klausur_options_frage_inhalt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frage',
            name='inhalt',
            field=models.CharField(default='?', max_length=50, verbose_name='Inhalt'),
        ),
    ]
