# Generated by Django 4.2.7 on 2023-11-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klausur', '0008_alter_frage_inhalt'),
    ]

    operations = [
        migrations.AddField(
            model_name='klausur',
            name='frage',
            field=models.ManyToManyField(to='klausur.frage', verbose_name='Fragen'),
        ),
    ]
