# Generated by Django 4.2.7 on 2023-11-26 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klausur', '0009_klausur_frage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klausur',
            old_name='frage',
            new_name='fragen',
        ),
    ]
