# Generated by Django 4.2.7 on 2023-11-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klausur', '0011_alter_frage_musterantwort_alter_frage_punkte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frage',
            name='platz',
        ),
        migrations.AlterField(
            model_name='klausurthema',
            name='position',
            field=models.IntegerField(default=1, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='klausurthema',
            name='seitenwechsel',
            field=models.BooleanField(default=False, verbose_name='Seitenwechsel im Anschluss'),
        ),
    ]
