# Generated by Django 4.2.7 on 2023-12-05 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("klausur", "0013_frage_bildbreite"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="klausur",
            options={
                "ordering": ["gruppe", "-termin"],
                "verbose_name": "Klausur",
                "verbose_name_plural": "Klausuren",
            },
        ),
    ]
