# Generated by Django 4.2.7 on 2023-12-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klausur', '0013_frage_bildbreite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klausur',
            options={'ordering': ['gruppe', '-termin'], 'verbose_name': 'Klausur', 'verbose_name_plural': 'Klausuren'},
        ),
        migrations.AddField(
            model_name='frage',
            name='bildmuster',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Bild Muster'),
        ),
    ]
