# Generated by Django 4.2.7 on 2024-01-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klausur", "0014_alter_klausur_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="frage",
            name="bildmuster",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Bild Muster"
            ),
        ),
    ]
