# Generated by Django 4.2.7 on 2024-04-04 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("klausur", "0015_frage_bildmuster"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teilnehmer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Name")),
                ("info", models.TextField(blank=True, null=True, verbose_name="Infos")),
            ],
            options={
                "verbose_name": "Teilnehmer",
                "verbose_name_plural": "Teilnehmers",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="klausur",
            options={"verbose_name": "Klausur", "verbose_name_plural": "Klausuren"},
        ),
        migrations.CreateModel(
            name="Gruppe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Bezeichnung")),
                (
                    "teilnehmer",
                    models.ManyToManyField(
                        to="klausur.teilnehmer", verbose_name="Teilnehmer"
                    ),
                ),
            ],
            options={
                "verbose_name": "Gruppe",
                "verbose_name_plural": "Gruppen",
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("punkte", models.IntegerField(default=0, verbose_name="Punkte")),
                (
                    "bemerkung",
                    models.TextField(blank=True, null=True, verbose_name="Bemerkung"),
                ),
                (
                    "frage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="klausur.frage",
                        verbose_name="Frage",
                    ),
                ),
                (
                    "klausur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="klausur.klausur",
                        verbose_name="Klausur",
                    ),
                ),
                (
                    "teilnehmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="klausur.teilnehmer",
                        verbose_name="Teilnhmer*in",
                    ),
                ),
            ],
            options={
                "verbose_name": "Antwort",
                "verbose_name_plural": "Antworten",
            },
        ),
    ]
