# Generated by Django 4.2.7 on 2024-04-02 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klausur', '0016_alter_klausur_options_klausur_fragen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teilnehmer',
            name='nummer',
        ),
    ]
