# Generated by Django 4.2.7 on 2024-04-04 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("klausur", "0016_teilnehmer_alter_klausur_options_gruppe_answer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="klausur",
            name="gruppe",
        ),
    ]
