# Generated by Django 4.2.7 on 2024-04-04 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("klausur", "0017_remove_klausur_gruppe"),
    ]

    operations = [
        migrations.AddField(
            model_name="klausur",
            name="gruppe",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="klausur.gruppe",
                verbose_name="Gruppe",
            ),
        ),
    ]
