# Generated by Django 4.2.7 on 2024-04-04 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("klausur", "0018_klausur_gruppe"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="klausur",
            options={
                "ordering": ["gruppe", "-termin"],
                "verbose_name": "Klausur",
                "verbose_name_plural": "Klausuren",
            },
        ),
    ]
