# Generated by Django 4.2.7 on 2024-04-02 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klausur', '0018_alter_teilnehmer_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teilnehmer',
            options={'ordering': ['name'], 'verbose_name': 'Teilnehmer', 'verbose_name_plural': 'Teilnehmers'},
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punkte', models.IntegerField(verbose_name='Punkte')),
                ('bemerkung', models.TextField(verbose_name='')),
                ('frage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klausur.frage', verbose_name='Frage')),
                ('klausur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klausur.klausur', verbose_name='Klausur')),
                ('teilnehmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klausur.teilnehmer', verbose_name='Teilnhmer*in')),
            ],
            options={
                'verbose_name': 'Antwort',
                'verbose_name_plural': 'Antworten',
            },
        ),
    ]
