# Generated by Django 4.2.7 on 2024-04-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klausur', '0019_alter_teilnehmer_options_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='bemerkung',
            field=models.TextField(verbose_name='Bemerkung'),
        ),
    ]
