# Generated by Django 4.2.7 on 2024-04-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klausur', '0021_alter_answer_bemerkung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='punkte',
            field=models.IntegerField(default=0, verbose_name='Punkte'),
        ),
    ]
