# Generated by Django 5.1.1 on 2025-06-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rahmenlehrplan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Version")),
                ("bereich", models.DateField(verbose_name="Bereich")),
                (
                    "description",
                    models.CharField(max_length=50, verbose_name="Beschreibung"),
                ),
                (
                    "bundesland",
                    models.CharField(
                        default="Baden-Württemberg",
                        max_length=50,
                        verbose_name="Beschreibung",
                    ),
                ),
                ("quelle", models.URLField(verbose_name="Quelle")),
            ],
            options={
                "verbose_name": "Rahmenlehrplan",
                "verbose_name_plural": "Rahmenlehrpläne",
            },
        ),
    ]
