# Generated by Django 5.1.1 on 2025-06-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lehrplan", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rahmenlehrplan",
            name="bereich",
            field=models.CharField(max_length=50, verbose_name="Bereich"),
        ),
        migrations.AlterField(
            model_name="rahmenlehrplan",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Beschreibung"),
        ),
    ]
