# Generated by Django 5.1.1 on 2025-06-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lehrplan', '0002_alter_rahmenlehrplan_bereich_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beruf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuerzel', models.CharField(max_length=5, verbose_name='Kürzel')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('beschreibung', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Beruf',
                'verbose_name_plural': 'Berufe',
            },
        ),
        migrations.CreateModel(
            name='Lernfeld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=5, verbose_name='Nummer')),
                ('inhalt', models.CharField(max_length=200, verbose_name='Inhalt')),
                ('stunden1', models.IntegerField(verbose_name='Zeitrichtwerte 1. Jahr')),
                ('stunden2', models.IntegerField(verbose_name='Zeitrichtwerte 2. Jahr')),
                ('stunden3', models.IntegerField(verbose_name='Zeitrichtwerte 3. Jahr')),
                ('beschreibung', models.TextField(verbose_name='Beschreibung')),
                ('berufe', models.ManyToManyField(to='lehrplan.beruf', verbose_name='Berufe')),
            ],
            options={
                'verbose_name': 'Lernfeld',
                'verbose_name_plural': 'Lernfelder',
            },
        ),
    ]
