# Generated by Django 5.1.1 on 2025-06-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lehrplan', '0003_beruf_lernfeld'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lernfeld',
            name='stunden1',
            field=models.IntegerField(default=0, verbose_name='Zeitrichtwerte 1. Jahr'),
        ),
        migrations.AlterField(
            model_name='lernfeld',
            name='stunden2',
            field=models.IntegerField(default=0, verbose_name='Zeitrichtwerte 2. Jahr'),
        ),
        migrations.AlterField(
            model_name='lernfeld',
            name='stunden3',
            field=models.IntegerField(default=0, verbose_name='Zeitrichtwerte 3. Jahr'),
        ),
    ]
