# Generated by Django 5.1.1 on 2025-06-06 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lehrplan', '0004_alter_lernfeld_stunden1_alter_lernfeld_stunden2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lernfeld',
            name='rahmenlehrplan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='lehrplan.rahmenlehrplan', verbose_name='Rahmenlehrplan'),
            preserve_default=False,
        ),
    ]
