# Generated by Django 5.1.1 on 2025-06-06 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lehrplan', '0005_lernfeld_rahmenlehrplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aubi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('kuerzel', models.CharField(max_length=5, verbose_name='Kürzel')),
            ],
            options={
                'verbose_name': 'Ausbilder',
                'verbose_name_plural': 'Ausbilder',
            },
        ),
        migrations.AlterModelOptions(
            name='lernfeld',
            options={'ordering': ['rahmenlehrplan', 'nummer'], 'verbose_name': 'Lernfeld', 'verbose_name_plural': 'Lernfelder'},
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laenge', models.IntegerField(verbose_name='cia Ausbildungseinheiten')),
                ('beschreibunge', models.TextField(verbose_name='Beschreibung')),
                ('aubi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lehrplan.aubi', verbose_name='Ausbilder')),
                ('lernfeld', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lehrplan.lernfeld', verbose_name='Lernfeld')),
            ],
            options={
                'verbose_name': 'Block',
                'verbose_name_plural': 'Blöcke',
            },
        ),
    ]
