# Generated by Django 5.1.1 on 2025-06-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lehrplan', '0006_aubi_alter_lernfeld_options_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='rahmenlehrplan',
            name='aktiv',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
    ]
