# Generated by Django 5.1.1 on 2025-06-09 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lehrplan', '0007_rahmenlehrplan_aktiv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='beschreibunge',
            new_name='beschreibung',
        ),
    ]
