# Generated by Django 5.1.1 on 2025-06-11 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lehrplan', '0008_rename_beschreibunge_block_beschreibung'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aubi',
            name='aktiv',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AddField(
            model_name='aubi',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
