# Generated by Django 5.1.1 on 2025-06-30 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lehrplan', '0009_aubi_aktiv_aubi_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['aubi', 'lernfeld'], 'verbose_name': 'Block', 'verbose_name_plural': 'Blöcke'},
        ),
    ]
