# Generated by Django 5.2.3 on 2025-12-06 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lehrplan', '0009_aubi_aktiv_aubi_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='beruf',
            name='lehrplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='lehrplan.rahmenlehrplan', verbose_name='Lehrplan'),
        ),
    ]
