# Generated by Django 5.1.1 on 2025-06-30 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lehrplan', '0010_alter_block_options'),
        ('stammdaten', '0002_ausbilder_fg_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='aubi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AubiRLP', to='stammdaten.ausbilder', verbose_name='Ausbilder'),
        ),
        migrations.DeleteModel(
            name='Aubi',
        ),
    ]
