# Generated by Django 5.1.1 on 2025-06-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lehrplan', '0011_alter_block_aubi_delete_aubi'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='inhalt',
            field=models.CharField(default='', max_length=30, verbose_name='Inhalt'),
            preserve_default=False,
        ),
    ]
