# Generated by Django 5.1.1 on 2024-10-15 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gruppe',
            options={'ordering': ['-activ', 'name'], 'verbose_name': 'Gruppe', 'verbose_name_plural': 'Gruppen'},
        ),
        migrations.AlterField(
            model_name='gruppe',
            name='short',
            field=models.CharField(max_length=10, verbose_name='Kürzel'),
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Jahr')),
                ('day', models.IntegerField(verbose_name='Tag')),
                ('daytime', models.CharField(max_length=2, verbose_name='Tageszeit')),
                ('content', models.CharField(max_length=50, verbose_name='Fach')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.gruppe', verbose_name='Gruppe')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.ausbilder', verbose_name='Ausbilder')),
            ],
            options={
                'verbose_name': 'Block',
                'verbose_name_plural': 'Blöcke',
                'ordering': ['group', 'year', 'day', 'daytime'],
            },
        ),
    ]
