# Generated by Django 5.1.1 on 2024-10-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_alter_block_options_block_kw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daytime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=2, verbose_name='Kürzel')),
                ('description', models.CharField(max_length=50, verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Tageszeit',
                'verbose_name_plural': 'Tageszeiten',
            },
        ),
    ]
