# Generated by Django 5.1.1 on 2024-10-15 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_daytime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='daytime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.daytime', verbose_name='Tageszeit'),
        ),
    ]
