# Generated by Django 5.1.1 on 2024-10-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
