# Generated by Django 5.1.1 on 2024-10-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ausbilder',
            options={'ordering': ['user'], 'verbose_name': 'Ausbilder', 'verbose_name_plural': 'Ausbilder'},
        ),
    ]
