# Generated by Django 5.1.1 on 2024-10-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0009_alter_ausbilder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausbilder',
            name='activ',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
    ]
