# Generated by Django 5.1.1 on 2024-10-21 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0010_ausbilder_activ'),
    ]

    operations = [
        migrations.CreateModel(
            name='AubiBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Datum')),
                ('wochentags', models.IntegerField(blank=True, choices=[(0, 'Montag'), (1, 'Dienstag'), (2, 'Mittwoch'), (3, 'Donnerstag'), (4, 'Freitag')], null=True, verbose_name='Wochentag)')),
                ('comment', models.TextField(verbose_name='Kommentar')),
                ('aubi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.ausbilder', verbose_name='Ausbilder')),
                ('daytime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.daytime', verbose_name='Tageszeit')),
            ],
            options={
                'verbose_name': 'AubiBlock',
                'verbose_name_plural': 'AubiBlocks',
            },
        ),
    ]
