# Generated by Django 5.1.1 on 2024-10-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0011_aubiblock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aubiblock',
            old_name='wochentags',
            new_name='day',
        ),
        migrations.AlterField(
            model_name='aubiblock',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Kommentar'),
        ),
    ]
