# Generated by Django 5.1.1 on 2024-10-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0012_rename_wochentags_aubiblock_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Bezeichnung'),
        ),
    ]
