# Generated by Django 5.1.1 on 2024-10-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0013_alter_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gruppe',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Bezeichnung'),
        ),
    ]
