# Generated by Django 5.1.1 on 2024-10-22 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0015_alter_block_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.ausbilder', verbose_name='Ausbilder'),
        ),
    ]
