# Generated by Django 5.1.1 on 2024-10-23 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0016_alter_block_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'Block', 'verbose_name_plural': 'Blöcke'},
        ),
        migrations.RemoveField(
            model_name='block',
            name='daytime',
        ),
    ]
