# Generated by Django 5.1.1 on 2024-10-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0017_alter_block_options_remove_block_daytime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['group', 'year', 'kw', 'day', 'daytime'], 'verbose_name': 'Block', 'verbose_name_plural': 'Blöcke'},
        ),
        migrations.AddField(
            model_name='block',
            name='daytime',
            field=models.CharField(choices=[('am', 'Vormittag'), ('pm', 'Nachmittag')], default='am', max_length=2, verbose_name='Tageszeit'),
            preserve_default=False,
        ),
    ]
