# Generated by Django 5.1.1 on 2024-10-23 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0018_alter_block_options_block_daytime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aubiblock',
            name='daytime',
        ),
    ]
