# Generated by Django 5.1.1 on 2024-10-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0019_remove_aubiblock_daytime'),
    ]

    operations = [
        migrations.AddField(
            model_name='aubiblock',
            name='daytime',
            field=models.CharField(choices=[('am', 'Vormittag'), ('pm', 'Nachmittag')], default='gt', max_length=2, verbose_name='Tageszeit'),
            preserve_default=False,
        ),
    ]
