# Generated by Django 5.1.1 on 2024-11-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0024_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Zeitpunkt'),
        ),
    ]
