# Generated by Django 5.1.1 on 2024-11-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0026_alter_block_daytime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aubiblock',
            name='daytime',
            field=models.CharField(choices=[('gt', 'Ganztag'), ('am', 'Vormittag'), ('pm', 'Nachmittag')], max_length=2, verbose_name='Tageszeit'),
        ),
        migrations.AlterField(
            model_name='block',
            name='daytime',
            field=models.CharField(choices=[('am', 'Vormittag'), ('pm', 'Nachmittag')], max_length=2, verbose_name='Tageszeit'),
        ),
    ]
