# Generated by Django 5.1.1 on 2024-11-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0027_alter_aubiblock_daytime_alter_block_daytime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='groups',
            field=models.ManyToManyField(blank=True, to='plan.gruppe', verbose_name='Gruppen'),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, to='plan.ausbilder', verbose_name='Ausbilder'),
        ),
    ]
