# Generated by Django 5.1.1 on 2025-06-30 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lehrplan', '0009_aubi_aktiv_aubi_user'),
        ('plan', '0029_alter_aubiblock_daytime'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='lehrblock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lehrplan.block', verbose_name='Ausbildungseinheit'),
        ),
    ]
