# Generated by Django 5.1.1 on 2025-06-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0030_block_lehrblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='content',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Info'),
        ),
    ]
