# Generated by Django 5.1.1 on 2025-06-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0031_alter_block_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausbilder',
            name='kuerzel',
            field=models.CharField(default='000', max_length=5, verbose_name='Kürzel'),
            preserve_default=False,
        ),
    ]
