# Generated by Django 5.1.1 on 2025-06-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0032_ausbilder_kuerzel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausbilder',
            name='kuerzel',
            field=models.CharField(max_length=10, verbose_name='Kürzel'),
        ),
    ]
