# Generated by Django 5.1.1 on 2025-06-30 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0033_alter_ausbilder_kuerzel'),
        ('stammdaten', '0002_ausbilder_fg_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aubiblock',
            name='aubi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stammdaten.ausbilder', verbose_name='Ausbilder'),
        ),
        migrations.AlterField(
            model_name='block',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stammdaten.ausbilder', verbose_name='Ausbilder'),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, to='stammdaten.ausbilder', verbose_name='Ausbilder'),
        ),
    ]
