# Generated by Django 5.1.1 on 2025-06-30 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0034_alter_aubiblock_aubi_alter_block_teacher_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ausbilder',
        ),
    ]
