# Generated by Django 5.1.1 on 2025-07-03 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0035_delete_ausbilder'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourFixe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(verbose_name='Zeitpunkt')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('gruppe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.gruppe', verbose_name='Gruppe')),
            ],
            options={
                'verbose_name': 'JourFixe',
                'verbose_name_plural': 'JourFixes',
            },
        ),
    ]
