# Generated by Django 5.2.3 on 2025-12-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lehrplan', '0013_beruf_lehrplan'),
        ('plan', '0036_jourfixe'),
    ]

    operations = [
        migrations.AddField(
            model_name='gruppe',
            name='berufe',
            field=models.ManyToManyField(to='lehrplan.beruf', verbose_name='Berufe'),
        ),
    ]
