# Generated by Django 4.2.7 on 2023-11-11 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bereich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Bezeichnung')),
                ('kommentar', models.TextField(blank=True, null=True, verbose_name='Kommentart')),
            ],
            options={
                'verbose_name': 'Bereich',
                'verbose_name_plural': 'Bereiche',
            },
        ),
        migrations.CreateModel(
            name='Aufgabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100, verbose_name='Aufgabe')),
                ('kommentar', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('termin', models.DateTimeField(blank=True, null=True, verbose_name='Termin')),
                ('erstellt', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('bearbeitet', models.DateTimeField(auto_now=True, verbose_name='Bearbeitet')),
                ('prio', models.IntegerField(default=0, verbose_name='Priorität')),
                ('erledigt', models.BooleanField(default=False, verbose_name='erledigt')),
                ('bereich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.bereich', verbose_name='Bereich')),
            ],
            options={
                'verbose_name': 'Aufgabe',
                'verbose_name_plural': 'Aufgaben',
            },
        ),
    ]
