# Generated by Django 4.2.7 on 2023-11-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aufgabe',
            options={'ordering': ['-prio', 'titel'], 'verbose_name': 'Aufgabe', 'verbose_name_plural': 'Aufgaben'},
        ),
    ]
